version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker: 
    - image: circleci/node:14.15.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install NPM
          command: 'npm i'
      - save_cache:
          name: Save NPM Package Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps: 
      - attach_workspace:
          at: ~/repo
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: build storybook
          command: 'npm run build-storybook'
      - store_artifacts:
          path: storybook-static
      - run:
          name: Deploy Storybook Production
          command: 'npm run deploy-storybook'
      - run:
          name: Publish package
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc | npm publish
          
  deploy-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy Storybook UAT
          command: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-once-uploaded
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
                - internal
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-storybook:
          requires:
            - build
          filters:
            branches:
              only:
                - development
                - internal
